### ISSUE TITLE
Unable to resolve github-api artifacts from Maven Central

### ISSUE THREAD

**Issue by msteiger** [github-api/github-api#195]
The source of the problem seems to be the incorrect `pom.xm` file for `org.jenkins-ci:annotation-indexer:1.4`. It reports `jenkins` as being the its parent, which is not in Central. Thus, the parent fails to resolve.

This issue has already been reported in slightly different contexts at [MVNCENTRAL-648](https://issues.sonatype.org/browse/MVNCENTRAL-648) and [JENKINS-27599](https://issues.jenkins-ci.org/browse/JENKINS-27599).

I would assume that only @kohsuke (who apparently has signed it) can edit the pom or upload a new one with a higher version number.

```
org.kohsuke:github-api:1.68
+--- commons-lang:commons-lang:2.6
+--- commons-codec:commons-codec:1.7
+--- com.fasterxml.jackson.core:jackson-databind:2.2.3
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.2.3
|    \--- com.fasterxml.jackson.core:jackson-core:2.2.3
+--- commons-io:commons-io:1.4
\--- com.infradna.tool:bridge-method-annotation:1.14
     \--- org.jenkins-ci:annotation-indexer:1.4 FAILED
```

**Comment by mikkelbd** [comment]
Any progress on this one @kohsuke? Would like to use the library, but version 1.70 still has the problem and thus can't be used with Maven.

**Comment by kohsuke** [comment]
I just attempted to upload org.jenkins-ci:jenkins:1.26 but it failed central sync rules: Project description missing, License information missing, Developer information missing.

So this involves releaseing new parent POM and update relevant dependencies. This is becoming a bit bigger problem than I would have hoped.

**Comment by mikkelbd** [comment]
Ok, thank you for the effort! I managed to bypass the problem by adding `http://repo.jenkins-ci.org/releases` as a Maven repository.

**Comment by henryju** [comment]
We were bitten by the same problem. Would be great to have it solved since central is supposed to be "self contained".

**Comment by szpak** [comment]
I agree that it would be good to not have to add an another artifact repository just for a parent pom.

**Comment by laughedelic** [comment]
> So this involves releaseing new parent POM and update relevant dependencies. This is becoming a bit bigger problem than I would have hoped.

@kohsuke if you are still able to resolve this, please do it 🙏 

This is a serious issue, because currently you force all users of your library to add that extra resolver to their builds and it's transitive, so if I have a library that depends on yours, all users of my library are forced to add this resolver 👎  

Current situation basically forces me to stop using it and consider migrating to another one, but I would like to avoid it.

**Comment by apratina** [comment]
This problem is not happening in the latest github-api:1.92 anymore.
