### ISSUE TITLE
GitHub 2 factor login

### ISSUE THREAD

**Issue by scj643** [github-api/github-api#292]
The api has no support for 2 factor authentication.

**Comment by Shredder121** [comment]
An OAuth token would be the way to go.
https://developer.github.com/v3/auth/#working-with-two-factor-authentication

So either implement the `X-GitHub-OTP` flow, or use an OAuth token.
Keep in mind that GitHub also recommends an OAuth token
>Because these authentication codes expire quickly, we recommend using the Authorizations API to [create an access token](https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization) and using that token to [authenticate via OAuth](https://developer.github.com/v3/#authentication) for most API access.

**Comment by madhephaestus** [comment]
Is there a workflow for application developers to use this? 

Some code examples of programmatically converting a user/pass combo into an oauth token? 

Specifically: I need a code example to get an OAuth token in the first place, given that in my code flow i have the username and password. I totally understand how to get a token out of pipeline, stick it in a hidden ~/.github text file, and can see it working. I have no idea how to use the Java code to get that token programmatically. 

I have an application using Github-api and would be very interested in a tested working example of using 2fa with the provided Java API (or a new API). Adding suggestions to re-parse  API calls that the library was designed to interface with leaves me very confused with where to start and how this suggestion fits with the already provided code examples.

**Comment by bitwiseman** [comment]
This works as expected.

**Comment by madhephaestus** [comment]
I can now confirm that the full 2 factor authentication workflow for requesting a token works.
