### ISSUE TITLE
SPOF check

### ISSUE THREAD

**Issue by KostyaSha** [github-api/github-api#321]
2 years ago i spent 4 months getting release with fixes. After it @oleg-nenashev got backup access to repo and maven central. Now it seems that story repeats.

@kohsuke please check that somebody else ( @stephenc , @oleg-nenashev ) has ability to do new releases.

**Comment by oleg-nenashev** [comment]
I do not have opportunity to properly maintain this repo, sorry

**Comment by kohsuke** [comment]
Ack, I'll find a few more people who are willing to cut a release

**Comment by johnou** [comment]
@kohsuke I think the last time I tried it failed when uploading the artifactes.

**Comment by bitwiseman** [comment]
@kohsuke This remains an issue. Care to grant me rights?

**Comment by oleg-nenashev** [comment]
It is not enough to have merge rights here. You would also need Maven
Central permissions to deploy it

**Comment by bitwiseman** [comment]
@oleg-nenashev
And they don't just give those out to rando's like me, I assume.

**Comment by oleg-nenashev** [comment]
Actually they grant it to anyone if the request is approved by the maintainer: https://issues.sonatype.org/browse/OSSRH-13404

@bitwiseman If you create a OSSRH account, I think we can ask for permissions for us both. @lanwen  and @KostyaSha maybe also interested as GitHub pluigin maintainers

**Comment by KostyaSha** [comment]
On my experience they can also grand perms of you are in push access level in github. But that depends on visibility.

**Comment by bitwiseman** [comment]
Done.  I've been informed that I now have permissions.

**Comment by bitwiseman** [comment]
Released v1.99.  I'm going to close this.  If we need to we can reopen it when SPOF becomes a concern again.
