### ISSUE TITLE
Fetching the issue URI for repositories with no issues

### ISSUE THREAD

**Issue by io7m** [github-api/github-api#334]
Hello.

I want to retrieve the issue API URI for a repository that, despite having issues enabled, has not yet actually had any issues filed. It seems that I need to get access to a value of type `GHIssue` in order to call the `getApiURL` on it, but in a repository that has no available issues, I can't!

What's the correct way to do this? Do I need to manually construct the URI myself?

**Comment by bitwiseman** [comment]
`repository.listIssues()`?
