### ISSUE TITLE
Unable to Deserialize Homepage in GHRepository

### ISSUE THREAD

**Issue by ivelichkovich** [github-api/github-api#370]
As of yesterday evening a jenkins job we have running using this repo has stopped working. We get a jackson deserialization error throwing a java IO exception here: https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/Requester.java#L608

It also mentions something about:  caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: java.io.StringReader@5474ef58; line: 1, column: 4222] (through reference chain: org.kohsuke.github.GHRepository["homepage"]))

We checked GHRepository homepage and this is a string but in our json from github homepage looks like:
"homepage":{"scheme":"http","user":null,"password":null,"host":"xxxxx-xx.github.com","port":null,"path":"/xxxx-xxxx/","query":null,"fragment":null}

So I think the issue is trying to put this object into a homepage string but we are not sure why this problem started suddenly. There have been no changes to the script we have.

**Comment by ivelichkovich** [comment]
The github api docs and when we curl the api we get homepage as a string but the json that we're trying to deserialize has it as an object. We're trying to track down the way the call is different.

**Comment by slide** [comment]
I'm seeing a similar issue, it looks like sometimes the "blog" component of an organization comes back as an object when inside of a "team" response. 

```json
{
  "name": "release team",
  "id": 2465297,
  "slug": "release-team",
  "description": null,
  "privacy": "secret",
  "url": "https:\/\/api.github.com\/teams\/2465297",
  "members_url": "https:\/\/api.github.com\/teams\/2465297\/members{\/member}",
  "repositories_url": "https:\/\/api.github.com\/teams\/2465297\/repos",
  "permission": "push",
  "created_at": "2017-09-02T00:16:13Z",
  "updated_at": "2017-09-02T00:16:13Z",
  "members_count": 0,
  "repos_count": 0,
  "organization": {
    "login": "IronLanguages",
    "id": 18199,
    "url": "https:\/\/api.github.com\/orgs\/IronLanguages",
    "repos_url": "https:\/\/api.github.com\/orgs\/IronLanguages\/repos",
    "events_url": "https:\/\/api.github.com\/orgs\/IronLanguages\/events",
    "hooks_url": "https:\/\/api.github.com\/orgs\/IronLanguages\/hooks",
    "issues_url": "https:\/\/api.github.com\/orgs\/IronLanguages\/issues",
    "members_url": "https:\/\/api.github.com\/orgs\/IronLanguages\/members{\/member}",
    "public_members_url": "https:\/\/api.github.com\/orgs\/IronLanguages\/public_members{\/member}",
    "avatar_url": "https:\/\/avatars1.githubusercontent.com\/u\/18199?v=4",
    "description": null,
    "name": "IronLanguages",
    "company": null,
    "blog": {
      "scheme": null,
      "user": null,
      "password": null,
      "host": null,
      "port": null,
      "path": "",
      "query": null,
      "fragment": null
    },
    "location": "",
    "email": null,
    "has_organization_projects": true,
    "has_repository_projects": true,
    "public_repos": 18,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "html_url": "https:\/\/github.com\/IronLanguages",
    "created_at": "2008-07-23T23:13:20Z",
    "updated_at": "2016-11-15T11:45:36Z",
    "type": "Organization"
  }
}```

This just recently started happening to my within the Jenkins project itself for the IRCBot. I am going to contact Github support.

**Comment by slide** [comment]
FYI, Github Support responded to my issue and said they deployed something that should fix the issue.
