### ISSUE TITLE
Branch name is not being correctly URL encoded

### ISSUE THREAD

**Issue by stephenc** [github-api/github-api#381]
See https://issues.jenkins-ci.org/browse/JENKINS-46898

Seems `#` is a valid character in a branch name but the URLs are not being correctly constructed causing it to be interpreted by GitHub as a document fragment identifier

**Comment by rmetzger** [comment]
I ran into the same issue with labels. For example a label "approved?" will not be resolved correctly.

**Comment by bitwiseman** [comment]
@rmetzger 
That's a separate issue, please file it.

**Comment by bitwiseman** [comment]
This issue has been fixed.  It will be in the next release.
