### ISSUE TITLE
Null value for GHPullRequestReview created date and updated date

### ISSUE THREAD

**Issue by soul2zimate** [github-api/github-api#450]
GHPullRequestReview values from GHPullRequest.listReviews() always contain Null for created date and updated date

**Comment by rmetzger** [comment]
I ran into the same issue. It seems that the GitHub API does not return the dates on the request: https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request

**Comment by rmetzger** [comment]
Did you find a solution to this problem?
