### ISSUE TITLE
where is upload picture api？how to upload pictures to issue？|我没找到图片上传API，如何远程上传图片到issue ？

### ISSUE THREAD

**Issue by geekyouth** [github-api/github-api#453]
where is upload picture api？how to upload pictures to issue from remote？
我没找到图片上传API，如何远程上传图片到issue ？

i just want to upload pictures from remote computer....
我想通过远程电脑上传图片到issue 里面。

now i can only upload picture from github web browser！！！that is too trouble！！！
现在只能通过github 网页端实现上传图片，这种方式太麻烦。

![image](https://user-images.githubusercontent.com/12899262/45266496-969c9500-b48e-11e8-8d9c-700fcde53652.png)

**Comment by oleg-nenashev** [comment]
Apparently it is a valid feature request, but I strongly suggest rewriting it if you want somebody to take it seriously

**Comment by geekyouth** [comment]
update

**Comment by nielsutrecht** [comment]
You're still being really rude. Please keep in mind that someone is building an awesome library for free for you.

Get rid of the 😤smiley and write it as a friendly request in English.

**Comment by geekyouth** [comment]
@nielsutrecht 

Does github offical has declared that all issues must be written in English?


_Sent from my MI Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bitwiseman** [comment]
This is the same issue as #452.
