### ISSUE TITLE
GitHub Api failing to create releases with .JAR files attached

### ISSUE THREAD

**Issue by ghost** [github-api/github-api#469]
We have been using the GitHub API plugin from out Jenkins CI/CD pipeline to create and update releases for a few months now.  At about 10am yesterday(10-22-18) the plugin started failing, throwing the following error:
`ERROR: {"message":"Error creating policy","request_id":"~~ID~~"}`
At first we assumed this was linked to the widespread GitHub issues that occurred on [October 21st and 22nd](https://status.github.com/messages).  Once those issues had subsided we noticed that this new issue was persisting.  Any insight into this issue would be very appreciated.

**Comment by bitwiseman** [comment]
Unclear what is going on.  Can you give any more information?

**Comment by bitwiseman** [comment]
Closing due to lack of response.
