### ISSUE TITLE
Provide OSGi bundle

### ISSUE THREAD

**Issue by acollign** [github-api/github-api#47]
This cool library deserves a OSGi bundle. I'm currently creating a bundle by wrapping  the library with its not-so-common dependencies embed [0]. I kept the groupId and will keep the version aligned with the library. 

I successfully tested this bundle on Adobe CQ 5.6.1 as-is. I'm also planning to write instructions for Apache Felix which might need the installation of some dependencies.

Feel free to comment commits, create issues. Feedback will be really appreciated.

[0] https://github.com/acollign/github-api-osgi

**Comment by acollign** [comment]
Hi @kohsuke , I'm suggesting to manage the OSGi bundle with a different artifact mainly because github-api has many dependencies that doesn't offer OSGi bundles at the minute.

It is therefore easier to embed those dependencies in a wrapper while keeping in mind that it has some drawbacks. Btw, I followed the instructions of the Apache Felix documentation [1].

[1] https://felix.apache.org/documentation/subprojects/apache-felix-commons/creating-bundles-using-bnd.html

**Comment by KostyaSha** [comment]
You can shade jar.

**Comment by acollign** [comment]
Hi @KostyaSha ,
Shading the jar is  another option but I'm not sure it makes more sense than the current approach.

**Comment by bitwiseman** [comment]
Closing as stale.
