### ISSUE TITLE
Implement archive/unarchive functionality

### ISSUE THREAD

**Issue by joaoe** [github-api/github-api#472]
Howdy.

`GHRepository` does not have an archive/unarchive feature.

To archive, a `GitHub.edit("archived", "true")` call is enough.

To unarchive, it is not possible from the REST API and need to be done manually in the web UI.

In case someone wants to implement an unarchive API:
send a POST request to `https://github.com/<organization>/<repository>/settings/archive` or `https://github.com/<organization>/<repository>/settings/unarchive`. The POST body contains:
`utf8=%E2%9C%93&authenticity_token=...&verify=<repository>`. The token `authenticity_token` is embedded in the HTML in the html form.
This will force to use a different set of URLs and scrape some HTML, so lets consider this out of scope.

**Comment by andrewlalis** [comment]
would it not be more intuitive to name the method simply `archive`?

**Comment by joaoe** [comment]
Hi. Could be, but archive is both a verb and a noun so for me at least, naming something as `archive` looks confusing. There are some options of verbs to use here, like `do` or `set`, or name it as `archiveRepository`.

**Comment by andrewlalis** [comment]
I think that if we want to be very explicit, the most java-style way to do it would be `setArchived(boolean isArchived)`

**Comment by joaoe** [comment]
Hi again. Been a bit away.

Are you one of the project maintainers ?

**Comment by andrewlalis** [comment]
No, sadly I'm just someone who is interested in having this functionality implemented.

**Comment by TV4Fun** [comment]
+1. This would be very nice to have.

**Comment by bitwiseman** [comment]
@joaoe @TV4Fun 
I've commented on #473.  If you're interested, please update the PR to address the comments and we can get this merged.

**Comment by bitwiseman** [comment]
I changed the method name to `archive()` and added a test for it.  
This will be in the next version, which should be released in the next few weeks.

**Comment by lumaxis** [comment]
Just coincidentally found this and wanted to leave a note that unarchiving via API is now possible: https://github.blog/changelog/2022-12-13-unarchive-a-repository-via-the-rest-api/

**Comment by bitwiseman** [comment]
@lumaxis 
Could you open a new issue asking for `unarchive` functionality to be added?
