### ISSUE TITLE
Ability to commit textContent directly to tree, without intermediate blobs

### ISSUE THREAD

**Issue by blacelle** [github-api/github-api#504]
https://github.com/kohsuke/github-api/issues/360 introduces a way to commit multiple files in a single commit. The library API suggests it is possible to build a tree from text content without creating blob manually with `org.kohsuke.github.GHTreeBuilder.textEntry(String, String, boolean)`.

However, this fails with:

    {"message":"Must supply tree.sha or tree.content","documentation_url":"https://developer.github.com/v3/git/trees/#create-a-tree"}

**Comment by spaceghost69** [comment]
Sha seems required despite docs...?

**Comment by iHatebug** [comment]
I also tried this and hit the same issue, may i know if there's any work around to commit multiple files in a single commit?

**Comment by bitwiseman** [comment]
Please help us in improve this project.  
#360 was committed before we added a framework that made adding tests easier.

@siordache 
I know it has been a while but as the submitter of the original change would you be willing to add some tests we could use as examples?

**Comment by siordache** [comment]
@bitwiseman I will look into it in the next few days.

**Comment by bitwiseman** [comment]
Fixed in #620

**Comment by siordache** [comment]
@spaceghost69 @blacelle @iHatebug
Until the fix goes live, see [this gist](https://gist.github.com/siordache/f2a895569de6f866877174376cf777d0) for a workaround.

**Comment by bitwiseman** [comment]
Live now in v1.100.  Thanks @siordache!
