### ISSUE TITLE
Add ETAG support to minimize API requests

### ISSUE THREAD

**Issue by docwhat** [github-api/github-api#505]
If we use `ETAG`s to make [conditional requests](https://developer.github.com/v3/#conditional-requests) then the `304 Not Modified` responses do not count against our API limit.

This could make our API requests faster and use up less of our API limit.

**Comment by bitwiseman** [comment]
This is already provided by `OkHttpConnector` when you have caching enabled.   I've improved the behavior recently but it was already present.
