### ISSUE TITLE
OkHttp3Connector uses a deprecated and now removed API in Okhttp 3.14.0

### ISSUE THREAD

**Issue by gastaldi** [github-api/github-api#506]
According to https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3140. `OkUrlFactory` was removed from okhttp 3.14.0, making the upgrade impossible when your application requires okhttp as the default mechanism for HTTP requests.

**Comment by bitwiseman** [comment]
Added `https://github.com/github-api/github-api/blob/master/src/main/java/org/kohsuke/github/extras/okhttp3/OkHttpConnector.java`

Marked old version as Deprecated. Or do we need to remove it in order to unblock upgrade?

**Comment by bitwiseman** [comment]
@gastaldi 
I believe this has been addressed in v1.99 using the new class noted above. If not, please comment and I'll reopen.
