### ISSUE TITLE
Request times out  if getPullRequests tries to get a large number of pages (140 pages)

### ISSUE THREAD

**Issue by HickeyHsu** [github-api/github-api#511]
Read Time out when getPullRequests list if there are more than 140 pages of PullRequests in a repo;

I want to grab a huge amount of pullrequests so I wonder whether there is a way to provide a method to allow me to set how many pages of pullrequest I want to get, so that I can get them in in batches.

thx very much.

**Comment by bitwiseman** [comment]
This is odd because when getting PullRequests, each page is a new request.  So, there shouldn't be any time out problem there.  Could you give an example of the code you're running?

**Comment by bitwiseman** [comment]
Closing due to non-response.
