### ISSUE TITLE
Inconsistency between createRef and getRef

### ISSUE THREAD

**Issue by dmarkhas** [github-api/github-api#518]
Currently createRef expects a fully qualified ref name ('refs/heads/master') while getRef prepends the 'refs/' and will fail if called with the same argument as createRef.
This is confusing, I suggest to align the APIs or at least prevent getRef from auto-adding 'refs/' to the path if the provided name already starts with 'refs/'.

**Comment by bitwiseman** [comment]
Agreed, this is an issue, but fixing has high potential to be a breaking change.
