### ISSUE TITLE
Add new event types 

### ISSUE THREAD

**Issue by bitwiseman** [github-api/github-api#519]
See https://issues.jenkins-ci.org/browse/JENKINS-57430

GitHub has added new events since this library was created.  The new events result in an exception being thrown for webhooks: 

```
java.lang.IllegalArgumentException: No enum constant org.kohsuke.github.GHEvent.CHECK_RUN
```

I don't have a list of event that need to be added aside from CHECK_RUN and CHECK_SUITE, but I'm sure there are more.

**Comment by thomas-riccardi** [comment]
Bump

Among other things this limits usage in Jenkins.

**Comment by strass** [comment]
I am hitting this issue in Jenkins now too

**Comment by bitwiseman** [comment]
@strass  @thomas-riccardi 
It is being worked on.
