### ISSUE TITLE
Querry commit does not work for me

### ISSUE THREAD

**Issue by alexanderm2018** [github-api/github-api#531]
not sure what is going on but these search returns all of the commits and not within the time range.
```
ghRepository.get().queryCommits().since(new Date(System.currentTimeMillis() - 7L * 24 * 3600 * 1000)).until(new Date(System.currentTimeMillis() - 1L * 24 * 3600 * 1000)).list()
```
Also `.from(sha)` return empty list?
Am I doing something wrong or it's a bug?

**Comment by bitwiseman** [comment]
If you do just `ghRepository.get().queryCommits()` what do you get? What repository are you trying this on?

**Comment by bitwiseman** [comment]
No response.  Closing.
