### ISSUE TITLE
Any plan for new releases?

### ISSUE THREAD

**Issue by tkbky** [github-api/github-api#569]
Thanks for this library, it's awesome.

I notice that the latest release is 1.95, which was published in Nov 2018. Is there any plan to make new releases? I'm requesting because I'm using some of the new APIs not available in 1.95, i.e. Github App, authenticating with JWT token, etc.

Would appreciate if there is official release that I can use, instead of through approach like [JitPack](https://jitpack.io).

**Comment by tkbky** [comment]
cc/ @bitwiseman

**Comment by bitwiseman** [comment]
@tkbky  
It is on my list to talk with @kohsuke about this soon.

**Comment by KostyaSha** [comment]
related to #321

**Comment by bitwiseman** [comment]
I now have permissions, I'll do an update this week.
