### ISSUE TITLE
createTeam with permission field deprecated in API but library still uses the field

### ISSUE THREAD

**Issue by asthinasthi** [github-api/github-api#617]
In https://developer.github.com/v3/teams/#create-team

`permission` field is deprecated. But the library still expects a permission field. https://github.com/github-api/github-api/blob/da11702f6815f658014f33ce724f0cd2e4501081/src/main/java/org/kohsuke/github/GHOrganization.java#L387

Is it on the roadmap to align the library with the deprecation?

I have created a PR: https://github.com/github-api/github-api/pull/619 to refactor this.

**Comment by bitwiseman** [comment]
Closed by #619
