### ISSUE TITLE
Shade the common dependencies in the library

### ISSUE THREAD

**Issue by oleg-nenashev** [github-api/github-api#630]
Currently GitHub API declares several dependencies, including okhttp, commons-lang, commons-io, etc. These dependencies were updated in 1.99 by Dependabot, and it leads to risks when using the library in components which already include older versions of the libraries. 

One of the examples: Jenkins Core and GitHub API Plugin which bundles the library. https://github.com/jenkinsci/github-api-plugin/pull/24 updated the version there while Jenkins static checkers ignored it due to the exclusions in POM.xml: https://github.com/jenkinsci/github-api-plugin/blob/master/pom.xml#L77-L80 . Basically such approach may explode at any moment.

There are two possible solutions:

* Revert library updates in 1.99, pin the library versions
* Shade the dependencies so that GitHub API becomes more portable. I would recommend it though it may require a significant effort

**Comment by bitwiseman** [comment]
@oleg-nenashev 
Could you include the link for instructions on how to go about shading?

**Comment by oleg-nenashev** [comment]
* https://maven.apache.org/plugins/maven-shade-plugin/
* https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html

**Comment by KostyaSha** [comment]
Or just stop blindly updating minimal required library versions in every repository?
