### ISSUE TITLE
Dont see how to search for all repositories for a given date range

### ISSUE THREAD

**Issue by pkasson** [github-api/github-api#639]
Investigating whether you can search for all repos for a date, such as:

show me all Java repos between 12/10/2019 and 12/10/2019

**Comment by bitwiseman** [comment]
@pkasson  Does this ability exist in the GitHub API?   
By " all repos for a date" do you mean " all repos created before/after the provided date"?  Or modified? Or ... ?

**Comment by pkasson** [comment]
Say I want to see all Java repos for a given date, like on Friday, December 13th and am doing this check today (the 13th).  There may be more added since this check, next week.

So, to assure I didn't miss any, I want to query it again, same thing - all on Friday the 13th - along with the other criteria.

**Comment by pkasson** [comment]
Is that possible ?

**Comment by bitwiseman** [comment]
@pkasson  
I do not know of a query for this in the github api (https://developer.github.com/v3/repos).

**Comment by pkasson** [comment]
I assumed that much, thanks for confirming !

**Comment by bitwiseman** [comment]
At this point, I'm going to say this is out of scope for this library. If you'd like to make a case for it being included, I'm happy to discuss further.
