### ISSUE TITLE
HTTP 401 Must specify two-factor authentication OTP code

### ISSUE THREAD

**Issue by heuermh** [github-api/github-api#641]
How might one specify or obtain an OTP code?

```java
GitHub github = GitHubBuilder.fromPropertyFile().build();
GHRepository repository = github.getRepository(groupId);
GHMilestone milestone = repository.getMilestone(milestoneId);
...
```

```
GHOTPRequiredException: {
  "message":"Must specify two-factor authentication OTP code.",
  "documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"
}: Server returned HTTP response code: 401, message: 'Unauthorized' for URL:
https://api.github.com/repos/username/repository: Server returned HTTP response
code: 401 for URL: https://api.github.com/repos/username/repository -> [Help 1]
```

Thank you in advance

**Comment by PauloMigAlmeida** [comment]
Hi @heuermh 

You might want to read this thread: https://github.com/github-api/github-api/pull/603

But the TL;DR; is:

*If* one has MFA configured then he/she may:

*  Use Personal Access Token as the access mechanism given the numerous security advantages (granular permissions)
* Implement through the use of a `Supplier<String>` function a way of programmatically obtain the OTP which is really dependent on which OTP one has configured on his/her account.

Here is where it was initially implemented.
https://github.com/github-api/github-api/pull/603/commits/e138c6fd61c7101e5b3aae5fbda3163d8765cbf6


One thing that it's worth mentioning is that GitHub is deprecating the access to certain endpoints if the access is made using user/pass combinations. If applicable to what you're doing, it may be in your best interest to move to Personal Tokens, OAuth apps or Github Apps instead.

Happy coding ;)

**Comment by heuermh** [comment]
> Use Personal Access Token as the access mechanism

Ah, I thought I was using the Personal Access Token mechanism.  With that, the OTP is not required?  Perhaps I have something misconfigured.

Thanks!

**Comment by PauloMigAlmeida** [comment]
My understanding is that once you have a PAT then the OTP won't be required to access GitHub's endpoints programmatically. Please test it and, in case I'm missing something out too, let me know ;)

**Comment by heuermh** [comment]
Thank you for your help, @PauloMigAlmeida!

On OSX I have been using Personal Access Token via Keychain Access but my `.github` file still referenced the old username/password credentials.

After specifying my Personal Access Token in `.github` the OTP is no longer required, as expected.

https://github.com/heuermh/github-changes-maven-plugin

Closing as Not an Issue
