### ISSUE TITLE
add 'has_projects' to GHRepository

### ISSUE THREAD

**Issue by BorisNaguet** [github-api/github-api#661]
Hello,

Support for repositories has been added with #425, but listing repositories returns an exception if the repositories tab has been disabled in settings.

Getting a repository returns a 'has_projects' that would be useful:
https://developer.github.com/v3/repos/#get
```json
  "has_issues": true,
  "has_projects": true,
  "has_wiki": true,
  "has_pages": false,
  "has_downloads": true,
```

Could you add it to GHRepository:
```java
    private boolean has_issues, has_wiki, fork, has_downloads, has_pages, archived;
```

Thanks

**Comment by bitwiseman** [comment]
@BorisNaguet 
Totally possible. PR's welcome.
