### ISSUE TITLE
Update repository description link to be https

### ISSUE THREAD

**Issue by timja** [github-api/github-api#671]
The repository description should match the README and be served over https

Before:
Java API for GitHub http://github-api.kohsuke.org

After:
Java API for GitHub http://github-api.kohsuke.org

**Comment by timja** [comment]
I meant the GitHub repository description

**Comment by bitwiseman** [comment]
@timja  Where?

**Comment by timja** [comment]
![image](https://user-images.githubusercontent.com/21194782/72932440-b79a1900-3d57-11ea-8193-ffa833de7e04.png)

**Comment by bitwiseman** [comment]
Doh.  fixed.
