### ISSUE TITLE
gitHttpTransportUrl has disappeared

### ISSUE THREAD

**Issue by jgournet** [github-api/github-api#775]
Ticket https://github.com/github-api/github-api/issues/403 asked to create a new method getHttpTransportUrl to replace the typo in gitHttpTransportUrl
That old gitHttpTransportUrl has now been removed, which is breaking https://plugins.jenkins.io/ghprb/ ... which is not maintained anymore

Any chance this could be re-added ?

**Comment by mveitas** [comment]
I just ran into this issue this morning and was scratching my head and finally found this issue you just opened. This is the commit that removed the method: https://github.com/github-api/github-api/commit/944d92bbb408dc7be91fcbe539a21762c6e0491a#diff-2573773dabfaf0a775ab7ec5ecb43548

As an alternative you can temp rollback to the v1.107 release which still has the method. In my case I was pulling the latest version of the plugin and when I spun up a new cluster this now broke.

**Comment by andrew-garland** [comment]
Also had the same issue with the git hub pull request builder breaking.

**Comment by bitwiseman** [comment]
Gah. :sob:  This method has been deprecated for many *years*.    This is why Jenkins can't have nice things.

It is my fault.  I'll reverse this change.

**Comment by samrocketman** [comment]
I merged and released https://github.com/jenkinsci/ghprb-plugin/pull/772 (I've been mostly inactive on the project the past two years).  I did a quick GitHub jenkinsci search and this plugin is the only Jenkins plugin using the deprecated API as far as I can tell.

REF: https://github.com/search?q=org%3Ajenkinsci+gitHttpTransportUrl&type=Code

**Comment by bitwiseman** [comment]
@samrocketman 
Thanks!
