### ISSUE TITLE
Contribution guide lists confirmation message that isn't printed anymore

### ISSUE THREAD

**Issue by chids** [github-api/github-api#785]
In https://github.com/github-api/github-api/commit/061e8bb6629a656f7803c717ce38562a2be3b8b9#diff-f5d253ed0b93a9c5f01efab67659fd77R39-R41 `System.out.println` statements in `WireMockStatusReporterTest.java` was commented out. These were printing the confirmation message referred to in step 4 of the "Setting up credential" section of the [contribution guidelines](https://github.com/github-api/github-api/blob/master/CONTRIBUTING.md).

The guide is still correct and following it works, there will however be no message printed at step 4.

**Comment by bitwiseman** [comment]
I probably did a global search and replace.  The right fix is to make the message appear again, either by uncommenting the line or using a logger.
